name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [
  { pattern = "vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "support.zoom.us.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.vpn.stupidworld.web.id", custom_domain = true },

  { pattern = "vpn.luckystup-id.xyz", custom_domain = true },
  { pattern = "ava.game.naver.com.vpn.luckystup-id.xyz", custom_domain = true },
  { pattern = "df.game.naver.com.vpn.luckystup-id.xyz", custom_domain = true },
  { pattern = "graph.instagram.com.vpn.luckystup-id.xyz", custom_domain = true },
  { pattern = "zaintest.vuclip.com.vpn.luckystup-id.xyz", custom_domain = true },
  { pattern = "support.zoom.us.vpn.luckystup-id.xyz", custom_domain = true },
  { pattern = "cache.netflix.com.vpn.luckystup-id.xyz", custom_domain = true },
]


[[kv_namespaces]]
binding = "SIREN"
id = "387eff0217a64551a18d0703bd7c3fe2"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bef63218-3a18-4f59-acac-28622247e22c"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/LuckyX2-Stup/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/LuckyX2-Stup/Siren/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/LuckyX2-Stup/Siren/refs/heads/master/web/link.html"
PROJECT_PAGE_URL = "https://raw.githubusercontent.com/LuckyX2-Stup/Siren/refs/heads/master/web/project.html"
